version: '3.8'

services:
  # MongoDB Database Service
  mongodb:
    image: mongo:7.0
    container_name: products-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: products_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - mongodb_config_dev:/data/configdb
    networks:
      - products-network-dev

  # Node.js API Service (Development)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    container_name: products-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/products_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - products-network-dev
    command: ["npm", "run", "dev"]

# Named volumes for data persistence
volumes:
  mongodb_data_dev:
    driver: local
  mongodb_config_dev:
    driver: local

# Custom network for service communication
networks:
  products-network-dev:
    driver: bridge

